apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: q2
  labels:
    team: {{team}}
spec:
  image: {{ image }}
  env:
    - name: BEHOV_TOPIC
      value: "privat-dagpenger-behov-v1-q2"
    - name: APPLICATION_ID
      value: "dp-regel-api-q2"
    - name: DATABASE_NAME
      value: "dp-regel-api-q2"
    - name: DATABASE_HOST
      value: "b27dbvl009.preprod.local"
    - name: KAFKA_SUBSUMSJON_TOPIC
      value: "privat-dagpenger-subsumsjon-brukt-q2"
  port: 8092
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 3
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - "https://dp-regel-api-q2.nais.preprod.local"
  secureLogs:
    enabled: true
  vault:
    enabled: true

