---        
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: teamdagpenger
  name: dp-regel-api-redis
  namespace: default
spec:
  image: redis:5-alpine # or a custom Redis-image
  port: 6379
  replicas: # A single Redis-app doesn't scale
    min: 1
    max: 1
  resources: # you need to monitor need your self
    limits:
      cpu: 250m 
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 256Mi
  service:
    port: 6379
---

apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: teamdagpenger
  name: dp-regel-api-redisexporter
  namespace: default
spec:
  image: oliver006/redis_exporter:v0.29.0-alpine
  port: 9121
  prometheus:
    enabled: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
  env:
    - name: REDIS_ADDR
      value: dp-regler-api-redis.default.svc.nais.local:6379
